# Practical 8

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv('/kaggle/input/california-housing-prices/housing.csv')

In [3]:
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()
x = iris.data
y = iris.target

In [5]:
df = pd.DataFrame(x, columns=iris.feature_names)
df['species'] = y
print(df.head)

<bound method NDFrame.head of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8  

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [7]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [8]:
k = 5
knn = KNeighborsClassifier(n_neighbors = k)

In [9]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [10]:
y_pred = knn.predict(x_test)

In [11]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 100.00%


In [12]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [13]:
from sklearn.metrics import classification_report
print("\confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

\confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [14]:
print("\ncorrect and incorrect Predictions: ")
for i in range(len(y_test)):
    correct = y_test[i]== y_pred[i]
    print(f"Actual: {iris.target_names[y_test[i]]}, Predicted: {iris.target_names[y_pred[i]]} - {'correct' if correct else 'wrong'}")


correct and incorrect Predictions: 
Actual: versicolor, Predicted: versicolor - correct
Actual: setosa, Predicted: setosa - correct
Actual: virginica, Predicted: virginica - correct
Actual: versicolor, Predicted: versicolor - correct
Actual: versicolor, Predicted: versicolor - correct
Actual: setosa, Predicted: setosa - correct
Actual: versicolor, Predicted: versicolor - correct
Actual: virginica, Predicted: virginica - correct
Actual: versicolor, Predicted: versicolor - correct
Actual: versicolor, Predicted: versicolor - correct
Actual: virginica, Predicted: virginica - correct
Actual: setosa, Predicted: setosa - correct
Actual: setosa, Predicted: setosa - correct
Actual: setosa, Predicted: setosa - correct
Actual: setosa, Predicted: setosa - correct
Actual: versicolor, Predicted: versicolor - correct
Actual: virginica, Predicted: virginica - correct
Actual: versicolor, Predicted: versicolor - correct
Actual: versicolor, Predicted: versicolor - correct
Actual: virginica, Predicted: v